# Generated by Django 4.2.7 on 2023-11-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_is_drawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_drawn',
            field=models.IntegerField(),
        ),
    ]
